config/routes.rb
Rails.application.routes.draw do

   root 'finances#index'
   
   resources :finances
   
   get 'newrecord' => 'static_pages#newrecord'

end

app/models/finance.rb
class Finance < ActiveRecord::Base
    validates :title, :amount, :date, presence: true
    
    def self.balance
      where("amount > ?", 0).sum("amount")
    end

    def self.debt
      where("amount < ?", 0).sum("amount")
    end
    
    def self.total
      sum("amount")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
    def index
        @finances = Finance.all
    end
    
    def create
        @finance = Finance.create(finance_params)
        if @finance.valid?
            flash[:success] = "Your finance has been added!"
        else
            flash[:alert] = "Woops! Looks like there has been an error!"
        end
        redirect_to root_path
    end
    
    def edit
        @finance = Finance.find(params[:id])
    end
    
    def update
      @finance = Finance.find(params[:id])
      if @finance.update(finance_params)
        flash[:success] = "The record has been updated!"
        redirect_to root_path
      else
        flash[:alert] = "Woops! Looks like there has been an error!"
        redirect_to edit_finance_path(params[:id])
      end
    end
    
    
    def destroy
      @finance = Finance.find(params[:id])
      @finance.destroy
      flash[:success] = "The record was successfully deleted!"
      redirect_to root_path
    end
    
    private
    
    def finance_params
        params.require(:finance).permit(:title, :amount, :date)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def newrecord
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finances_helper.rb
module FinancesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/finances/edit.html.erb
<%= simple_form_for @finance, method: :patch do |f| %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.input :date %>
  <%= f.submit 'Update Record', class: 'btn btn-success' %>
<% end %>

app/views/finances/index.html.erb
  <div class="panel panel-default">
    <div class="panel-body">
      <h2>Balance: Rs. <%= Finance.balance %></h2>
      <h2>Debt   : Rs. <%= Finance.debt %></h2>
      <h2>Total  : Rs. <%= Finance.total %></h2>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
            <table class="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Title</th>
                  <th>Amount</th>
                  <th></th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                  <% @finances.each do |finance| %>
                    <tr>
                      <td><%= finance.date %></td>
                      <td><%= finance.title %></td>
                      <td>Rs. <%= finance.amount %></td>
                      <td><%= link_to 'Edit', edit_finance_path(finance), class: 'btn btn-sm btn-success' %></td>
                      <td><%= link_to 'Delete', finance_path(finance), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %></td>
                    </tr>
                  <% end %>                      
              </tbody>
            </table>
      </blockquote> 
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>$ Financer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Audiowide|Open+Sans:300,400,600,700" rel="stylesheet">
  
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
</head>
<body>
<div id="wrap">  
  <%= render 'shared/nav' %>
  <br>
  <div class = "container">
    <div class = "row">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
    </div>
  </div>
</div><!-- wrap -->

<%= render 'shared/foot' %>
  
</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_foot.html.erb
<div class ="foot">
  <div class="ft">
    <div class="footer text-center">
        <p>By Deepak L. Karna</p>
        <p>© TECHRISE <%= Date.today.year %> All Rights Reserved</p>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="navbar-header">
  <div class="navbar-default">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><i class="icon-money"></i> Financer</a>
  </div><!-- navbar-default -->
</div><!-- navbar-header -->

<div class="static">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'All Finances', root_path %></li>
            <li><%= link_to 'New Record', newrecord_path %></li>
        </ul>
    </div><!-- /.navbar-collapse -->
</div><!-- static -->

app/views/static_pages/newrecord.html.erb
<div class="panel panel-default">
    <div class="panel-body">
      <blockquote>
          <div class="modal-body">
            <%= simple_form_for Finance.new do |f| %>
              <%= f.input :title %>
              <%= f.input :amount %>
              <%= f.input :date %>
              <br>
              <%= f.submit 'Create Record', class: 'btn btn-primary' %>
            <% end %>
          </div>
      </blockquote>
    </div>
</div>